name: Esther Build Action

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-windows:
        runs-on: windows-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 14.16.0

            - name: Install Packages
              run: |
                  npm install

            - name: Build
              run: |
                  npm run build
              env:
                  VITE_APP_ELECTRON_API_URL: /api
                  VITE_APP_ELECTRON_API_URL_DEV: http://127.0.0.1:10754
                  GH_TOKEN: ${{ secrets.ESTHERMUSIC }}

            - name: artifact setup
              uses: actions/upload-artifact@v2
              with:
                  name: EstherMusic-win-setup
                  path: release/**/*setup*.exe
                  if-no-files-found: ignore

            - name: artifact portable
              uses: actions/upload-artifact@v2
              with:
                  name: EstherMusic-win-portable
                  path: release/**/*.7z
                  if-no-files-found: ignore

    build-MacOS:
        runs-on: macos-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 14.16.0

            - name: Install Packages
              run: |
                  npm install

            - name: Build
              run: |
                  npm run build
              env:
                  VITE_APP_ELECTRON_API_URL: /api
                  VITE_APP_ELECTRON_API_URL_DEV: http://127.0.0.1:10754
                  GH_TOKEN: ${{ secrets.ESTHERMUSIC }}

            - name: artifact x64
              uses: actions/upload-artifact@v2
              with:
                  name: EstherMusic-mac-x64
                  path: release/**/*-x64.dmg
                  if-no-files-found: ignore

            - name: artifact arm64
              uses: actions/upload-artifact@v2
              with:
                  name: EstherMusic-mac-arm64
                  path: release/**/*-arm64.dmg
                  if-no-files-found: ignore

            - name: artifact universal
              uses: actions/upload-artifact@v2
              with:
                  name: EstherMusic-mac-universal
                  path: release/**/*-universal.dmg
                  if-no-files-found: ignore
